name: Gerar Cobrinha de Contribuições

on:
  schedule:
    - cron: "0 */6 * * *" # Roda a cada 6 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: platane/snk@v2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
          # Você pode remover o .gif se quiser apenas o .svg
          # e o .svg se quiser apenas o .gif
          
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output # Onde a imagem será salva
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
